# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

iperf3:
  hosts:
    - host: 192.168.86.30

command_line:
  - switch:
      name: Bluetooth Stereo Connection
      command_on: "bluetoothctl connect 89:41:F8:40:93:1B"
      command_off: "bluetoothctl disconnect 89:41:F8:40:93:1B"
      command_state: "bluetoothctl info 89:41:F8:40:93:1B"
      value_template: "{{ 'Connected: yes' in value }}"
      scan_interval: 10
      icon: >
        {% if is_state('switch.bluetooth_stereo_connection', 'on') %}
          mdi:bluetooth-connect
        {% else %}
          mdi:bluetooth-audio
        {% endif %}

script:
  pair_bluetooth_stereo:
    alias: Pair Bluetooth Stereo
    icon: mdi:bluetooth-transfer
    sequence:
      - action: command_line.send_command
        data:
          command: "bluetoothctl pair 89:41:F8:40:93:1B && bluetoothctl trust 89:41:F8:40:93:1B"

logger:
  default: warning
  logs:
    custom_components.ha_onecontrol: warning
